import type {Metadata} from 'next';
import './globals.css';
import { GlobalContextProvider } from '@/components/';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </head>
      <body>
        <GlobalContextProvider>{children}</GlobalContextProvider>
      </body>
    </html>
  );
}
