import type { Metadata } from "next";
import "./globals.css";
import { MainHeader } from "@/components";
import TanStackProvider from "@/providers/TanStack";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <TanStackProvider>
          <MainHeader />
          {children}
        </TanStackProvider>
      </body>
    </html>
  );
}
